### ISSUE TITLE
csv file output incorrect header.

### ISSUE THREAD

**Issue by mr-pmillz** [EatonChips/yalis#1]
The csv file header appears to be misaligned as the companyID is the last item.

### current csv file output format
```csv
companyID,firstname,lastname,occupation,link
rick,astley,VP Accounting at foo Bar Baz,rastley,1234567
```

### Expected csv file output
```csv
firstname,lastname,occupation,link,companyID
rick,astley,VP Accounting at foo Bar Baz,rastley,1234567
```

Pretty cool tool by the way! 💯

**Comment by EatonChips** [comment]
Oops, thanks for pointing this out! Realigned the header.
